### ISSUE TITLE
for2py front end: translation of constant integer arguments to functions does not work

### ISSUE THREAD

**Issue by skdebray** [ml4ai/delphi#162]
The translation of constant integer arguments to subprograms does not work.  The input Fortran program is:
```
C test constant integer arguments to functions

      subroutine f(n)
      implicit none
      integer n

      if (n .eq. 0) then
          write(*,10) n
      else
          write(*,10) n
      end if

 10   format(I5)
      end subroutine f
C **********************************************
      program main
      call f(0)
      stop
      end program main
```
The translation to Python goes smoothly:
```
$ java fortran.ofp.FrontEnd --class fortran.ofp.XMLPrinter --verbosity 0 tmp.f > ast.xml
$ ~/Research/for2py/delphi/delphi/translators/for2py/scripts/translate.py -f ast.xml -g pickle.pkl -i tmp.f
$ ~/Research/for2py/delphi/delphi/translators/for2py/scripts/pyTranslate.py -f pickle.pkl -g out.py
```
However, when I try to run the resulting Python file `out.py` I get an exception:
```
$ python3.7 out.py
Traceback (most recent call last):
  File "out.py", line 25, in <module>
    main()
  File "out.py", line 22, in main
    f(0)
  File "out.py", line 11, in f
    if (n[0] == 0):
TypeError: 'int' object is not subscriptable
```
The code for the generated Python file `out.py` is:
```
from typing import List
import math
from fortran_format import *
from for2py_arrays import *

def f(n: List[int]):
    format_10: List[str] = []
    format_10 = ['I5']
    format_10_obj = Format(format_10)
    
    if (n[0] == 0):
        write_list_10 = [n]
        write_line = format_10_obj.write_line(write_list_10)
        file_10.write(write_line)
    else:
        write_list_10 = [n]
        write_line = format_10_obj.write_line(write_list_10)
        file_10.write(write_line)
    

def main():
    f(0)            # <<< CULPRIT
    return

main()
```
This needs to be fixed.  @pratikbhd let me know if you want to discuss how best to handle this.

**Comment by skdebray** [comment]
The bug seems to have been fixed.  Thanks. :)
